### ISSUE TITLE
math section revision

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/FwdInvToolkit#44]
update and revise math section.  Update with the following criteria:

- [x] General clarity #12 #23 
- [ ] updated algorithms and examples #20
- [ ] update screenshots #19 
- [ ] include literature citations #22 
- [ ] Add conceptual diagrams #21 
- [ ] unify math notation #24
