### ISSUE TITLE
forward section revision

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/FwdInvToolkit#45]
update and revise forward section.  Update with the following criteria:

- [x] General clarity #12 #23 
- [x] updated algorithms and examples #20
- [x] update screenshots #19 
- [ ] include literature citations #22 
- [ ] Add conceptual diagrams #21 
- [ ] unify math notation #24
