### ISSUE TITLE
inverse section revision

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/FwdInvToolkit#46]
update and revise inverse section.  Update with the following criteria:

- [ ] General clarity #12 #23 
- [ ] updated algorithms and examples #20
- [ ] update screenshots #19 
- [ ] include literature citations #22 
- [ ] Add conceptual diagrams #21 
- [ ] unify math notation #24
